# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierent',
            name='returned_at',
            field=models.DateTimeField(null=True),
        ),
    ]
