# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_rent', '0002_auto_20180331_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierent',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies_catalog.Movie'),
            preserve_default=False,
        ),
    ]
