# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 15:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies_rent', '0004_auto_20180331_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movierent',
            name='created_by',
        ),
        migrations.AddField(
            model_name='movierent',
            name='rent_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rent_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
