# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 15:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_rent', '0005_auto_20180331_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierent',
            name='returned_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returned_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
