# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_rent', '0006_auto_20180331_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierent',
            name='rent_by',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='movierent',
            name='returned_by',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
