# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rent_amt',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
